### ISSUE TITLE
Update documents for HashIndex, TreeIndex, Queue, Bag about the condition when contained entries are dropped / enhance the drop timing

### ISSUE THREAD

**Issue by beckend** [wvwwvwwv/scalable-concurrent-containers#150]
```rust
use std::{sync::{atomic::{AtomicUsize, Ordering}, Arc}, time::Duration};
use color_eyre::eyre::{eyre, Result};
use once_cell::sync::Lazy;
use scc::HashIndex;

static CELL: Lazy<AtomicUsize> = Lazy::new(AtomicUsize::default);

struct Test{}

impl Drop for Test {
  fn drop(&mut self) {
    CELL.fetch_add(1, Ordering::SeqCst);
  }
}

#[tokio::main]
async fn main() -> Result<()> {
  color_eyre::install()?;

  drop(Test{});
  assert_eq!(CELL.load(Ordering::Acquire), 1);

  let map_index = HashIndex::new();
  let key = 0_usize;

  map_index
    .insert(key, Arc::new(Test{}))
    .map_err(|_| eyre!("Failed to insert"))?;
  map_index.remove_async(&key).await;
  assert!(!map_index.contains(&key));

  tokio::time::sleep(Duration::from_secs(5)).await;
  assert_eq!(CELL.load(Ordering::Acquire), 2);

  Ok(())
}
```

```shell
p-0190b042-81e4-7091-bb84-3f97fcf2c7a0/src/main.rs"
   Compiling p-0190b042-81e4-7091-bb84-3f97fcf2c7a0 v0.1.0 (/tmp/rust-playgrounds/p-0190b042-81e4-7091-bb84-3f97fcf2c7a0)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.32s
     Running `target/debug/p-0190b042-81e4-7091-bb84-3f97fcf2c7a0`
The application panicked (crashed).
Message:  assertion `left == right` failed
  left: 1
 right: 2
Location: src/main.rs:33
```

```toml
# Cargo.toml
[package]
name = "p-0190b042-81e4-7091-bb84-3f97fcf2c7a0"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
once_cell = "*"
scc = "*"

[dependencies.color-eyre]
version = "*"

[dependencies.tokio]
version = "*"
features = ["full"]
```

This also applies to `TreeIndex`, `Queue`, `Bag`.
